### PR TITLE
Add tag support for images

### PR DESCRIPTION
**Pull request by AlexZeitler**
* buildImage
* downloadImage
* hasImage
* startContainer
* getRunningContainersFor

### CODE REVIEW

**Comment by goloroden** [comment]
LGTM :-)

Thanks a lot for your great work, this really is very, very helpful :-)

IMHO there is just one thing I'd like to discuss with you before merging it: We have different kinds of signatures (we've had this before, but now it's more obvious):

- Some functions take an image name and tag as two string parameters,
- some use an options object,
- some use a single string with a colon in it.

I think for the ease of use it would be helpful to unify all these signatures. My personal favorite is using an options object, as this is the most future-ready and extensible way.

What do you think about this?
And: Would you mind to implement this as part of this PR?

**Comment by AlexZeitler** [comment]
TBH I've been thinking about the different signatures also and I would prefer streamlining them in an options object.

I can do this.

Also there are some broken tests (they were already broken when I started implementing tags support) which I would like to fix.

**Comment by goloroden** [comment]
Great, thanks :-))

Regarding the tests … uhm, yes, this would be helpful as well. It just makes me wonder that you say that some of the tests were already broken … which ones?

(On my machine, they all work perfectly right now.)

But anyway, of course it would be great if you could fix them :-)

**Comment by AlexZeitler** [comment]
If I remember it correctly, mostly around restart policy.
One error you can also see in the [circleci build output](https://circleci.com/gh/thenativeweb/crew/86).

**Comment by goloroden** [comment]
Regarding the tests on CircleCI you are definitely right - they have never been run successfully, but this is due to limitations of Docker support on CircleCI. Simply said, some things aren't supported there, such as (IIRC) stopping and removing containers. So ... it's questionable whether the tests will be able to run on CircleCI in the near future. But of course, if you find a way to do it, this would be awesome :-)

Running the tests locally, I think there should be no errors, but this may depend on the Docker version you (and me) are using.

**Comment by AlexZeitler** [comment]
This is the current `grunt` / `grunt test`output using Docker 1.8.2 and Docker Machine 0.4.0 on Ubuntu:

```
⋙  grunt
Running "eslint:server" (eslint) task


Running "mochacli:all" (mochacli) task


  DockWorker
Test container running...
    options
      ✓ contains the options that were set within the constructor.
    ping
      ✓ is a function.
      ✓ throws an error if callback is missing.
    hasImage
      ✓ is a function.
      ✓ throws an error if name is missing.
      ✓ throws an error if callback is missing.
      ✓ returns true if the specified image is available. (54ms)
      ✓ returns true if the image specified by name and tag is available. (375ms)
      ✓ returns false if the specified image is not available. (48ms)
    downloadImage
      ✓ is a function.
      ✓ throws an error if name is missing.
      ✓ throws an error if callback is missing.
      ✓ returns an error if the specified image could not be downloaded. (2884ms)
      ✓ does not return an error if the specified image was downloaded. (4921ms)
      ✓ downloads latest if no tag is specified (3587ms)
      ✓ downloads specified image if tag is specified (7397ms)
    buildImage
      ✓ is a function.
      ✓ throws an error if options are missing.
      ✓ throws an error if directory is missing.
      ✓ throws an error if dockerfile is missing.
      ✓ throws an error if name is missing.
      ✓ throws an error if callback is missing.
      ✓ builds an image. (306ms)
      ✓ builds an image by name and tag. (533ms)
      ✓ include all files if no .dockerignore file is given. (2298ms)
      ✓ excludes files specified in .dockerignore file. (2544ms)
      ✓ runs the preBuild hook before building the image. (2311ms)
      ✓ returns an error if the image can not be built. (104ms)
    startContainer
      ✓ is a function.
      ✓ throws an error if options are missing.
      ✓ throws an error if image is missing.
      ✓ throws an error if name is missing.
      ✓ throws an error if callback is missing.
      ✓ does not return an error if the container was started. (626ms)
      ✓ does not return an error if the container was started using name and tag. (7723ms)
      restart policy
        1) defaults to never.
      port forwardings
      environment variables
      volumes
      links
      network.hosts
    stopContainer
    getLogs
    getRunningContainersFor

  crew


  35 passing (54s)
  1 failing

  1) DockWorker startContainer restart policy defaults to never.:
     Uncaught AssertionError: Expected {
  killed: false,
  code: 1,
  signal: null
} to be null.
      at test/DockWorkerTests.js:546:45
      at ChildProcess.exithandler (child_process.js:651:7)
      at maybeClose (child_process.js:755:16)
      at Process.ChildProcess._handle.onexit (child_process.js:822:5)

```

**Comment by goloroden** [comment]
I'm still on 1.7.1, maybe this causes this behavior.

**Comment by AlexZeitler** [comment]
Ok, the first thing that breaks the tests, is [line 545 in DockWorkerTests.js](https://github.com/AlexZeitler/crew/blob/master/test/DockWorkerTests.js#L545):

```
childProcess.exec('docker kill ' + id + ' && docker rm -f ' + id, function (err) {
```

It looks like the container already stopped and this causes kill to return an error (I think this behavior has been introduced in Docker 1.8 as some of my sh-scripts also failed after updating from 1.7.x to 1.8).

Workaround:

```
childProcess.exec('docker kill ' + id + ' | true && docker rm -f ' + id, function (err) {
```

This causes to fail the kill command silently and only break the test if the final rm fails.
Ok?

**Comment by goloroden** [comment]
Hmmmm … not convinced ;-)

This *may* break on Docker 1.7, if `kill` goes bonker. Hence I'd opt for only supporting the new way and leave the workaround for older versions aside.

I think this is okay as the remote API itself changes heavily quite often, and we are not backwards compatible anyways, so I think it's fine to expect to be able to run on the latest version only.

So I think if you use a way that works on 1.8 correctly, you do not have to take care of 1.7 as well.

Okay for you?

**Comment by AlexZeitler** [comment]
Well, the question is: shouldn't the container in question still run so that the `kill` never fails?

**Comment by goloroden** [comment]
Maybe I got your sentence

> It looks like the container already stopped and this causes kill to return an error (I think this behavior has been introduced in Docker 1.8 as some of my sh-scripts also failed after updating from 1.7.x to 1.8).

wrong. What is the reason for the container having already stopped? If this is unintentionally, then of course you are right.

**Comment by AlexZeitler** [comment]
If I change the code around line 545 like this, I can asure that the `kill` is the root cause of failing the test:

```
childProcess.exec('docker kill ' + id, function(killErr) {
  assert.that(killErr).is.null();
  childProcess.exec('docker rm -f ' + id, function (err) {
    assert.that(err).is.null();
    done();
  });
});
```

`assert.that(killErr).is.null();` fails:

```
Uncaught AssertionError: Expected {
  killed: false,
  code: 1,
  signal: null
} to be null.
```

`docker ps` shows no running container and `docker ps -a` shows me that the `crew-test` container already stopped.

`docker logs crew-test` shows this output:

```
Test container running...
```

But no errors. So the question is: should the container have stopped already or is it expected to be still running?

**Comment by goloroden** [comment]
I've just had a look at the code for the test box, and apparently the container shall actually exit. So, basically, usage of `kill` here seems to be superfluous. Hmmm, I wonder why we included it?!?

**Comment by AlexZeitler** [comment]
So it is safe to remove the `kill`?

**Comment by goloroden** [comment]
I think so.

**Comment by AlexZeitler** [comment]
Ok, it looks better now ;-) Off to the next one...

**Comment by AlexZeitler** [comment]
```
  1) DockWorker startContainer volumes mounts a single volume.:
     Uncaught AssertionError: Expected {
  code: 'ECONNRESET'
} to be null.
      at Request._callback (test/DockWorkerTests.js:724:42)
      at Socket.socketOnEnd [as onend] (http.js:1568:9)
      at _stream_readable.js:929:16
```

The container in question has crashed:

```
⋙  docker logs crew-test 
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/data1/foo.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Server.<anonymous> (/app.js:8:14)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:473:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_server.js:324:22)
    at emitOne (events.js:77:13)
```

**Comment by AlexZeitler** [comment]
Interesting things going on... if I run the container like this:

```
docker run -d --name crew-test -p 3000:3000 -v testBox/tobeMounted:/data1 thenativeweb/crew-test
```

It is starting, stays available and the logs show no error.

But I can't bash into it like this
```
docker exec -it crew-test /bin/bash
```
It shows no error but is existing to my host bash immediately.

**Comment by goloroden** [comment]
Try `sh` instead of `bash`.

The image we use does not have a `bash` installed.

**Comment by AlexZeitler** [comment]
Well, that works fine :smile:

**Comment by AlexZeitler** [comment]
So it looks like the mapping doesn't work when being triggered from crew.

**Comment by goloroden** [comment]
Yes … as far as I can see, the file should actually be there. So this seems to indicate that mounting the volume did not work as expected in Docker 1.8.

**Comment by AlexZeitler** [comment]
Ok, looks like `container.start` also requires to get the `binds` option passed in:

Using this, `/data1` is available in the container...

```
container.start({
      'Binds': ['/home/alex/code/crew/test/testBox/toBeMounted:/data1']
    }, function (err) {
      if (err) {
        return callback(err);
      }
      callback(null, container.id);
    });
```

**Comment by goloroden** [comment]
As said, I think that this may have changed in the Docker API … things change quite often there :-/

**Comment by AlexZeitler** [comment]
Yeah, I'll try to fix it.

**Comment by AlexZeitler** [comment]
:grin: 
Ok the last one was my fault... I forgot to copy to the `crew` source to my local Docker machine before running the test...

More details [here](https://github.com/docker/machine/issues/1577).

So all tests are green now :tada: 

Will add some details about running the tests using Docker Machine in the `README`.

**Comment by AlexZeitler** [comment]
@goloroden I think we're ready to merge.

**Comment by goloroden** [comment]
This is really great :-)

I'll have a closer look at it within the next 2 to 3 days and then merge it.

Thank you very much for your great help :-)

**Comment by AlexZeitler** [comment]
Thanks 👍🏻

**Comment by goloroden** [comment]
I updated the docs to ES6 style, and am releasing a new version now…

**Pull request merged**
